# Generated by Django 4.1.7 on 2023-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CK', 'Cakes'), ('BC', 'Biscuits'), ('BD', 'Breads'), ('BK', 'Books'), ('BU', 'Flowers Buke'), ('GA', 'Gift Articles')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(verbose_name=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(verbose_name=2),
        ),
    ]
