# Generated by Django 4.1.7 on 2023-03-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0003_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='UserRegister',
        ),
    ]
