# Generated by Django 4.1.7 on 2023-03-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_paymeny_id',
            new_name='razorpay_payment_id',
        ),
    ]
